### ISSUE TITLE
When RabbitMQ Restarts...

### ISSUE THREAD

**Issue by jkida** [subzerocloud/pg-amqp-bridge#10]
```
ERROR:amqp::session: Error in reading loop: Protocol("Connection reset by peer (os error 104)")
ERROR:amqp::session: Error dispatching closing packet to a channel
ERROR:amqp::session: Error dispatching closing packet to a channel
... waits for next notify
```
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(BrokenPipe)', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Do you have any recommendations on a strategy to most reliably guarantee notify messages make it to rabbit?

When i restart rabbitMQ the bridge hangs until the next notify event at which time it terminates. Which means if I restart rabbitMQ i must restart the bridge otherwise I am guaranteed to miss 1 event at minimum.
Would it make sense to terminate as soon as the "Connection reset by peer" error is thrown, or just initiate the retry procedure I saw running startup?

**Comment by ruslantalpa** [comment]
This week the "reconnect" logic will be implemented which should be enough for most scenarios.
As for a general strategy i would recommend to carefully consider the type of events you want to forward and split them into 2 categories.
- events you absolutely can not drop (usually related to payments) and for them, whenever you send the event from the database (or maybe don't even send them to rabbit), make also a copy of the event in a "table" so basically use a db table as a queue (https://blog.2ndquadrant.com/what-is-select-skip-locked-for-in-postgresql-9-5/). This is a very reliable and performant method for these type of events (it's event used by stripe, can't find the link now).
- events for which you can tolerate a few seconds (per month) of occasional disconnect. For them pg-amqp-bridge is enough (with the upcoming reconnect feature). To make it even more stable (assuming your pg and rabbit are stable) you can modify pg-amqp-bringe to also set correlationId property for each message it sends (the value should be unique to each message) then have 2 pg-amqp-bridge processes running and both streaming the same events in parallel, and on the other end, the "clients" (or even a custom rabbit plugin) can de-dup based on this value (though i think this is overkill, the effort should go into making pg/bridge/rabbit communication stable)

**Comment by steve-chavez** [comment]
There is now a reconnection feature https://github.com/subzerocloud/pg-amqp-bridge/pull/11, that will retry the PG/RMQ connection when it's lost. For the RMQ case it'll retry the connection and when it succeeds the pending notifications will be sent.
