### ISSUE TITLE
Can't connect to PostgreSQL database

### ISSUE THREAD

**Issue by kishyr** [subzerocloud/pg-amqp-bridge#12]
Hi,

I can't to connect to my PostgreSQL database (running `pg-amqp-bridge` with PostgREST). 

This is the error I get:
`thread '<unnamed>' panicked at 'Could not connect to PostgreSQL: Io(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("invalid message length") }) })', /checkout/src/libcore/result.rs:859`

Here is the backtrace:
```
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at ./checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at ./checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at ./checkout/src/libstd/sys_common/backtrace.rs:60
             at ./checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at ./checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at ./checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at ./checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at ./checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at ./checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at ./checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: pg_amqp_bridge::spawn_listener_publisher::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
             at ./checkout/src/libpanic_unwind/lib.rs:98
  13: <F as alloc::boxed::FnBox<A>>::call_box
  14: std::sys::imp::thread::Thread::new::thread_start
             at ./checkout/src/liballoc/boxed.rs:650
             at ./checkout/src/libstd/sys_common/thread.rs:21
             at ./checkout/src/libstd/sys/unix/thread.rs:84
  15: start_thread
  16: clone
```

Could someone please point me in the right direction?

**Comment by steve-chavez** [comment]
Which version of PostgreSQL are you using? OS?

Also check your postgres connection uri(`postgres://user:pass@host:port`) if it contains reserved characters you might need to percent encode them.

**Comment by kishyr** [comment]
Hi,

I'm using PostgreSQL 9.6 on Ubuntu 14.04 LTS. 

I initially did have a problem where Postgres on Azure automatically appends `@my-server-name` to each username created on Postgres when trying to authenticate, and got a different error message for that (`Invalid '@' character`) but after URL-encoding the `@` character, this is the only error I get now. There doesn't seem to be anything else that needs to be encoded.  There are `-`s in the username, would that also need to be URL-encoded?

**Comment by kishyr** [comment]
Correction: Postgres is version 9.6, but since it's hosted as an Azure service, I'm not sure what OS it runs on. My docker master is running Ubuntu 14.04 and I'm running `pg-amqp-bridge` as a docker instance.

**Comment by steve-chavez** [comment]
The `-` chars should be safe, when the connection fails do you get retrying? Which pg-amqp-bridge version are you using? if it's latest(`0.0.6`) there should be a message like:
```
Attempting to connect to PostgreSQL..
<Error here>
Retrying the PostgreSQL connection in 2 seconds..
<Error here>
Retrying the PostgreSQL connection in 4 seconds..
......
```

**Comment by kishyr** [comment]
After upgrading to `latest` / `0.0.6` from Docker Hub, I now get the following:

```
Attempting to connect to PostgreSQL..
Error(Io(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("invalid message length") }) }))
Retrying the PostgreSQL connection in 1 seconds..
Error(Io(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("invalid message length") }) }))
Retrying the PostgreSQL connection in 2 seconds..
Error(Io(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("invalid message length") }) }))
Retrying the PostgreSQL connection in 4 seconds..
Error(Io(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("invalid message length") }) }))
Retrying the PostgreSQL connection in 8 seconds..
Error(Io(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("invalid message length") }) }))
Retrying the PostgreSQL connection in 16 seconds..
```

**Comment by kishyr** [comment]
I think I've narrowed down this issue. My PostgreSQL server requires connection over SSL. What should I specify in `POSTGRESQL_URI` to be able to connect over SSL?

**Comment by steve-chavez** [comment]
Right now there's no SSL connection support, see this line https://github.com/subzerocloud/pg-amqp-bridge/blob/master/src/main.rs#L52 that has `TlsMode::None`, that would have to be changed to `SslMode:Require` as described in this issue https://github.com/sfackler/r2d2-postgres/issues/7.

**Comment by steve-chavez** [comment]
Also you could try disabling SSL on your Azure potsgres instance with https://docs.microsoft.com/en-us/azure/postgresql/concepts-ssl-connection-security#using-the-azure-portal and see if the connection now works to see if that's indeed the problem.

**Comment by kishyr** [comment]
It was pretty strange. At first I received the `invalid message length` error, but after restarting the server I started to received an SSL-related error (not the one you mentioned above, but similar). I think it was Azure's custom SSL-must-be-on error message. 

Everything started working when I turned off SSL on the Azure instance. It's not ideal though, but I'm limiting access to the server from a specific IP range so it's OK for now. Would you be able to add SSL support to your feature-list?

**Comment by kishyr** [comment]
I see there it's been discussed on that project since 2015 but nothing has come of it.  Thanks for all your help. I'm going to close this issue now.
