### ISSUE TITLE
Not getting Postgres notifications

### ISSUE THREAD

**Issue by kishyr** [subzerocloud/pg-amqp-bridge#13]
Hi,

I am able to successfully connect to both my Postgres and RabbitMQ servers on my production environment but for some reason `pg-amqp-brdige` doesn't receive any notifications from Postgres.  

On my staging and dev environments, it works fine and I can see from the `pg-amqp-bridge` logs that it's receiving and forwarding messages correctly. All instances are running on docker tag 0.0.6.

I created a simple Node.js script that listens to a specific channel on the production Postgres server and it is able to output all notifications sent to it, so I definitely know Postgres working. If I manually create and publish a message on RabbitMQ, my services that listen to RabbitMQ fetch those messages and react to them, so I know RabbitMQ also works. 

It just seems like `pg-amqp-bridge` is not getting or listening to Postgres in production. I don't see any logs that indicate it is receiving anything from Posgres, like I do on my staging and dev environments. 

I've set `RUST_LOG=debug` but can't see any errors being thrown. 

My `INFO` log output looks like this:

```
Attempting to connect to AMQP server..
INFO:amqp::session: Session initialized
Connection to AMQP server successful
Attempting to connect to PostgreSQL..
Connection to PostgreSQL successful
Listening on n13s...
Listening on user_events...
```

Can someone point me in the right direction? I've been trying to troubleshoot for the past day and am getting nowhere.

**Comment by ruslantalpa** [comment]
paste the following things
- bridge configuration (how exactly are you starting it, the command line)
- the postgres query using which you generate the event
- how are you checking if the messages end up in in your rabbitmq server?
- the list of exchanges/queues in your rabbit that are linked to the bridge (rabbitadmin print screen or the output of a command line)
- how are you checking that the messages are not reaching rabbit?

**Comment by kishyr** [comment]
Hi,

**1. bridge configuration (how exactly are you starting it, the command line)**
Running it from a docker container using docker-compose:

```docker
  pg_amqp_bridge:
    image: subzerocloud/pg-amqp-bridge:0.0.6
    links:
      - rabbitmq
    environment:
      - POSTGRESQL_URI=***
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - AMQP_URI=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq//
      - BRIDGE_CHANNELS=n13s:n13s,user_events:user_events
    depends_on:
      - rabbitmq
    restart: always
```

**2. the postgres query using which you generate the event**
```sql
drop schema if exists rabbitmq cascade;
create schema rabbitmq;
grant usage on schema rabbitmq to public;

create or replace function rabbitmq.send_message(
  channel text,
  routing_key text,
  message text) returns void as $$
     
  select  pg_notify(
    channel,  
    case when routing_key is not null and routing_key <> '' 
	  then routing_key || '|' 
    else '' end || message
  );
$$ stable language sql;
```

**3. how are you checking if the messages end up in in your rabbitmq server?**

Checking RabbitMQ admin graphs, as well as the `pg_amqp_bridge` docker logs. 
In the logs, I see the following from my staging and dev instances:
`INFO:pg_amqp_bridge: "n13s" -> Exchange "n13s" ( ... )`
`INFO:pg_amqp_bridge: "user_events" -> Exchange "user_events" ( ... )`
But in production that does not happen. My Node.js RabbitMQ listener does not get notified either. If I paste in the JSON generated by the SQL `rabbitmq.send_message` function into RabbitMQ admin and send it, then my Node.js script gets it.

**4. the list of exchanges/queues in your rabbit that are linked to the bridge (rabbitadmin print screen or the output of a command line)**

Exchanges:
<img width="575" alt="screen shot 2018-04-03 at 08 33 39" src="https://user-images.githubusercontent.com/6758/38233512-0c227fe8-371b-11e8-8182-39092c9517fb.png">

Queues:
<img width="727" alt="screen shot 2018-04-03 at 08 32 31" src="https://user-images.githubusercontent.com/6758/38233518-1047c4b6-371b-11e8-9b8b-33d8532d0ed0.png">


**5. how are you checking that the messages are not reaching rabbit?**

1. I'm looking at RabbitMQ admin directly and it is not reporting that it received anything. The 'Total' column doesn't increase (liked it does on Staging)
2. My Node.js listener doesn't perform any action 
3. I'm looking at the `pg_amqp_bridge` docker logs and it is not outputting anything

The Postgres server is sending messages as I wrote a simple Node.js script to connect to the Postgres server, issue it a `LISTEN user_events` command, and then output all `notifications` sent. I can see Postgres is generating and sending messaging using the SQL function I pasted above (2).

**Comment by ruslantalpa** [comment]
first, set the log level as `RUST_LOG=info` (not sure if debug works) to see if the bridge is getting the messages
second, your exchanges are of type direct (compare the exchange type and binding key with your dev setup), so the binding key from exchange to the queue needs to match exactly with the routing key of your message so if you have `(e) n13s --(apple)--> (q) n13s`
a message should be generated similar to `rabbitmq.send_message('n13s', 'apple', 'Hi!');`

**Comment by ruslantalpa** [comment]
try generating an event manually like this in your database (maybe there is a problem with your triggers) using any sql client (run this query)

`NOTIFY user_events, 'signup|Hi'`

**Comment by kishyr** [comment]
Okay I tried that and monitored the `pg_amqp_bridge` logs — nothing. When I started my test Node.js listener that only look out for `user_events` notifications, it gets them and outputs them.

**Comment by ruslantalpa** [comment]
i think somewhere you mentioned you are on azure and it seems to support some config parameters
https://docs.microsoft.com/en-us/azure/postgresql/concepts-server-logs
specifically, try setting `log_statement` to `all` (and maybe other postgresql logging parameters) and then once you start the bridge, check the logs, see if the "connect" gets logged, also see if you get `LISTEN user_events` query executed by the bridge logged

if you use the starter kit, this is already implemented so compare the db log from the dev env to the production env and see if you can spot a difference, where is the point that logs start to be different (basically you need to see 3 events, connect, listen, notify)

**Comment by ruslantalpa** [comment]
seems like this was an azure thing, maybe it's fixed now, closing
