### ISSUE TITLE
ERROR:  payload string too long

### ISSUE THREAD

**Issue by ArturFormella** [subzerocloud/pg-amqp-bridge#17]
Hello! 
Is it possible to sent message to rabbit without NOTIFY?
PostgreSQL's NOTIFY has 6000 chars limit.

**Comment by ruslantalpa** [comment]
In this project no. In cases like this what you would do is generate a message sending over only the row id  and a few esencial colums, and on the other end the worker would use that id and request the full info from the db.
As a concept, another way to stream changes from the database (but not any event at will) is to use logical decoding api https://github.com/confluentinc/bottledwater-pg
