### ISSUE TITLE
Setup meet a problem in Centos7.6

### ISSUE THREAD

**Issue by longwenxp** [subzerocloud/pg-amqp-bridge#18]
OpenSSL incorrect version.
./pg-amqp-bridge
./pg-amqp-bridge: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
[root@iz2ze9d7x8qidftw27oxqsz bin]# find / -name libssl.so.1.0.*
/usr/lib64/libssl.so.1.0.2k
[root@iz2ze9d7x8qidftw27oxqsz bin]# ln -s /usr/lib64/libssl.so.1.0.2k /usr/lib64/libssl.so.1.0.0
[root@iz2ze9d7x8qidftw27oxqsz bin]# ./pg-amqp-bridge
./pg-amqp-bridge: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[root@iz2ze9d7x8qidftw27oxqsz bin]# find / -name libcrypto.so.1.0.*
/usr/lib64/libcrypto.so.1.0.2k
[root@iz2ze9d7x8qidftw27oxqsz bin]# ln -s /usr/lib64/libcrypto.so.1.0.2k /usr/lib64/libcrypto.so.1.0.0
[root@iz2ze9d7x8qidftw27oxqsz bin]# ./pg-amqp-bridge
./pg-amqp-bridge: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./pg-amqp-bridge)
./pg-amqp-bridge: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./pg-amqp-bridge)
./pg-amqp-bridge: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./pg-amqp-bridge)

 I don't know what to do now.

**Comment by ruslantalpa** [comment]
Try running it as docker https://github.com/subzerocloud/pg-amqp-bridge/blob/master/README.md#running-as-docker-container

Or compile it on your system

**Comment by longwenxp** [comment]
Thanks a lot. But I don't know how to compile it? make &&make install ??

**Comment by steve-chavez** [comment]
Note that the bridge won't work with openssl 1.1.0. This is because of the rust-amqp lib: https://github.com/Antti/rust-amqp/issues/43.

To compile natively, your system would have to provide an openssl 1.0.* version.

An option for the codebase might be to migrate to https://github.com/sozu-proxy/lapin.
