### ISSUE TITLE
Could not connect to AMQP: invalid port number

### ISSUE THREAD

**Issue by MarianoGomezBidondo** [subzerocloud/pg-amqp-bridge#25]
When i try to run as a docker image on Ubuntu 18 with posgres local but rabbitmq i remote server with:

`docker run --rm -it -net=host \
-e POSTGRESQL_URI="postgresql://user:pas@server.com:5432/basename" \
-e POSTGRESQL_CHANNEL="test" \
-e AMQP_URI="amqp://user:pass@remoteserver.com:5672//" \
-e AMQP_QUEUE_NAME="test" \
fgribreau/postgresql-to-amqp`

i get this:

   Finished release [optimized] target(s) in 0.37 secs
     Running `target/release/postgresql-to-amqp`
Could not connect to AMQP: invalid port number
thread 'main' panicked at 'Could not run reactor: Error { repr: Custom(Custom { kind: Other, error: StringError("invalid port number") }) }', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:92
   9: core::result::unwrap_failed
  10: postgresql_to_amqp::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: <unknown>

**Comment by ruslantalpa** [comment]
how is `fgribreau/postgresql-to-amqp` from your example related to `subzerocloud/pg-amqp-bridge`?

These are completely different projects.
