### ISSUE TITLE
Connect to Postgres using ssl mode

### ISSUE THREAD

**Issue by rizky** [subzerocloud/pg-amqp-bridge#26]
I tried to connect to Postgres db that requires ssl mode, but I got this error

> app[pg-amqp-bridge] info  Error(Db(DbError { severity: "FATAL", parsed_severity: Some(Fatal), code: SqlState("28000"), message: "no pg_hba.conf entry for host \"xxxx\", user \"xx\", database \"xxx\", SSL off", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("auth.c"), line: Some(520), routine: Some("ClientAuthentication") })) 

Stumbled upon this old issue with enhancement tag https://github.com/subzerocloud/pg-amqp-bridge/issues/12

Is this now supported in pg-amqp-bridge?

**Comment by ruslantalpa** [comment]
no, but it might be only a question of upgrading this lib. https://github.com/subzerocloud/pg-amqp-bridge/blob/master/Cargo.toml#L17

when i get some free time i'll look at it along with merging the other PR

**Comment by patrickmichalina** [comment]
Any attempts been made to update this to work  with ssl? @ruslantalpa

**Comment by ruslantalpa** [comment]
@patrickmichalina i think i made a small attempt (simply changing the lib version) but got some conflicts between amqp/postgres libs (both working with different ssl versions).

I rewrote the entire thing with better features [here](https://github.com/subzerocloud/pg-event-proxy-example) though it's not FOSS

If you manage to upgrade the libs i'll merge the pr.
