### ISSUE TITLE
Hearthbeat connection to AMQP proxy

### ISSUE THREAD

**Issue by pfranck** [subzerocloud/pg-amqp-bridge#27]
I got a issue when i'm connectiong the  bridge towards a cluster of rabbitmq behind a proxy.
ERROR:amqp::session: Error in reading loop: Protocol("failed to fill whole buffer")
ERROR:amqp::session: Error dispatching closing packet to a channel

This error seems to happen because the connection was closed. I would like to know if the heartbeat system offer by Rabbitmq is implemented https://www.rabbitmq.com/heartbeats.html

**Comment by ruslantalpa** [comment]
There is no heartbeat support in the amqp lib used https://github.com/Antti/rust-amqp 
`Missing things: No heartbeats support`
