### ISSUE TITLE
Can messages be lost on network failure?

### ISSUE THREAD

**Issue by tiagosmx** [subzerocloud/pg-amqp-bridge#30]
Can messages be lost when the connection between PostgreSQL and pg-amqp-bridge service is down?

This is something important to be discussed.

**Comment by ruslantalpa** [comment]
Yes, this is ho pg notify command works, if there is no client to receive the message it's missed but it's not hard to to implement a solution to mitigate this.
Here is an example https://github.com/subzerocloud/pg-event-proxy-example/blob/master/postgres/1_events.sql
Basically the function that generates the event checks if the "proxy" is connected before performing NOTIFY and if it's temporarily unavailable, stores the message in a events table until the proxy reconnects.

Alternatively [pg-event-proxy](https://github.com/subzerocloud/pg-event-proxy-example/blob/master/postgres/1_events.sql) supports event forwarding based on `WAL`
