### ISSUE TITLE
How to fix: ConnectionRefused?

### ISSUE THREAD

**Issue by Oleg26Dev** [subzerocloud/pg-amqp-bridge#32]
I have PostgreSQL installed on m y local machine on port:5433 , it is running, also I run RabbitMQ docker and then run pg-amp-bridge-docker
 docker run --rm -it --net=host -e POSTGRESQL_URI="postgres://postgres@localhost:5433" -e AMQP_URI="amqp://localhost//" -e BRIDGE_CHANNELS="pgchannel1:task_queue,pgchannel2:direct_exchange,pgchannel3:topic_exchange" subzerocloud/pg-amqp-bridge
Attempting to connect to PostgreSQL..
Error { kind: Connect, cause: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }
Retrying the PostgreSQL connection in 1 seconds..
...
what is incorrect? how to fix?

**Comment by ruslantalpa** [comment]
When using docker, localhost means the container itself.
Try `host.docker.internal` instead of localhost
