### ISSUE TITLE
Question about HA

### ISSUE THREAD

**Issue by xleliberty** [subzerocloud/pg-amqp-bridge#5]
Hi, 
i'm currently evaluating this project in one of ours, but i got a question .

how are you planning to work on cases where HA is needed ? 

We should need only one bridge working on an instance, and as long as the main bridge is out for some time, a second one should be up. Have you already work on this kind of uses cases ?

Thanks

Xavier

**Comment by ruslantalpa** [comment]
if you can tolerate a few seconds disconnect then when running it in docker, you could set a health check command and when it fails it will just be restarted.
another solution is to have two separate processes  and set correlationId on messages then implement logic on consumers to ignore duplicate events based on that property


I would go for docker/healthcheck and really evaluate if a few sec of downtime once in a while is such a bad thing. One probably can tune this to be as low as 1-2s when things crash

**Comment by xleliberty** [comment]
Hi, thank you for your answer.
The main purpose is implementing a webhooks system, and i would like to avoid risks of not sending an important change.

Some kind of correlationId could be a nice thing.  Maybe some sort of mechanism where we could provide this ID the same manner we provide the routing key , with a pipe, the bridge would then forward this ID to rabbit ?

Regards
Xavier

**Comment by ruslantalpa** [comment]
yes, that's the idea. should be relatively easy to implement

**Comment by danigosa** [comment]
May it be easier, as they do in pg_cron extension, to just enable the extension in master mode and disable when hot standby? Then auto enable when the instance is promoted. This way is totally seamless in HA mode, as you don't have to worry about anything, as the master is the only one sending messages to Rabbitmq and the very same extensions adapt to the HA failover process.

**Comment by ruslantalpa** [comment]
@danigosa in most "cloud" envs you can't have your custom extensions

**Comment by danigosa** [comment]
@ruslantalpa depends on what you mean for _cloud_, we got Kubernetes in the cloud (managed) and Postgresql is just one deployment more with HA, meaning we have full control of the postgresql instances. If you mean Database as a Service, yes you are right, cloud providers DaaS do not allow custom extensions _normally_. Being that said, I'm interested in the full control HA solution scenario, which seems simpler as feasible, I can't see a way to have a master-slave with this extension without any control of the instances to do something that do not break HA, as I see it only master should produce messages to rabbit, and being the master down and therefore promoted the slave to master (and connections proxied to the new master) you lost the ability to run them. 

We were looking for a solution for ampq bridge, we have full control of our instances in HA, for now we don't have to start the project but soon we have, and no pg_ampq nor this one or others are fully committed to HA or are abandoned or outdated. First solution that came to our minds is to do it at application level as extensions are not ready, maybe we think to contribute to the extension allowing HA with activation/deactivation depending on the mode. Any idea where to start?

**Comment by ruslantalpa** [comment]
A slave by definition will not produce events since events are only generated on write events (triggers/stored procedures) and since there are no events generated, pg-amqp-bridge will simply not send any (each instance has a bridge connected). Why bother with detecting which instance is the master.
Also on the HA thing, i can almost guarantee that PostgreSQL in RDS with read replicas will be more HA then a custom solution :) unless you have a TON o experience managing PG. and PG in Kuberneties ... you are braver then I am :)

**Comment by ruslantalpa** [comment]
My above comment/logic works only if NOTIFY commands are no streamed to replicas through WAL and i can't seem to find a clear answer if that happens or not (after a short superficial search).

**Comment by danigosa** [comment]
@ruslantalpa RDS is very limited in terms of non-standard extensions, unfortunately I can list 3 or 4 extensions not coming with PG by default nor being supported in any PG managed service being Google SQL or Amazon RDS or any other (like Citus, Timescale, pg_cron, etc.). I agree with you that for simple web or easy projects, small to medium sized, RDS is preferred and your current solution and ideas are ok, and believe if I could go for RDS I would have gone this way, but bigger and weird-requirements projects cannot leave with RDS and custom solutions must come in place.

**Comment by djmccormick** [comment]
What would a simple health check look like for pg-amqp-bridge?

**Comment by ruslantalpa** [comment]
@djmccormick I would an end to end check with he following logic.
* have a RPC in the db that just generates an "healthcheck" event (maybe with a timestamp param/event)
* have a healthcheck script that first registers with rabbit to receive healthcheck events (worker) then calls the above rpc (either calling through http for connecting to the db) and checks if it received the event it generated itself on the other end
