### ISSUE TITLE
Add support for persistent delivery mode

### ISSUE THREAD

**Issue by Deimos** [subzerocloud/pg-amqp-bridge#6]
Would it be possible to add an option to change the delivery mode of the published messages to persistent? This would make it so that messages can be persisted to disk and won't be lost if rabbitmq is restarted (assuming the queues were defined as durable).

Thanks for the work on this project, it's great as a simple way to get postgresql events into rabbitmq.

**Comment by ruslantalpa** [comment]
This would be good feature, would you like to try a PR, it would not be hard to implement, event if someone does not know rust?

IT's basically adding a new config parameter here https://github.com/subzerocloud/pg-amqp-bridge/blob/master/src/main.rs#L11
then passing that value all the way to this line https://github.com/subzerocloud/pg-amqp-bridge/blob/master/src/lib.rs#L108
where the property `delivery_mode` is set based on the config

**Comment by Deimos** [comment]
Checking the pg-amqp-bridge source code this morning to see if it was already possible somehow was actually the first time I've ever looked at Rust code at all, so I definitely don't have any experience. I can try a PR if you'd like though, thanks for the info about the places I'll need to look.

**Comment by steve-chavez** [comment]
Implemented in #8, now there's a `DELIVERY_MODE` env var. Closing.

**Comment by Deimos** [comment]
Nice, thanks very much for implementing that @antikantian.
